Repository sofiialives/mafia-club, pull requests merged in 2024-04, with the labels that each got.

#3 added header and footer without styles
  public/icons/facebook 1.svg
  public/icons/instagram.svg
  public/icons/logo.svg
  public/icons/telegram.svg
  public/icons/tiktok 1.svg
  public/icons/whatsapp.svg
  public/images/Image game 3.png
  public/images/Image game 5.png
  public/images/Image game 6.png
  public/images/Image game 7.png
  public/images/Image game 9.png
  public/images/Rectangle 10.png
  public/images/Rectangle 11.png
  public/images/Rectangle 12.png
  public/images/Rectangle 4.png
  public/images/Rectangle 8.png
  public/images/first.png
  public/images/mask.png
  public/images/second.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/Logo.tsx
  src/components/NavBar/NavBar.tsx
Labels: enhancement

#6 Home
  package-lock.json
  package.json
  public/images/38jO.gif
  public/images/eyes.png
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(legal)/modal/(.)privacy/page.tsx
  src/app/(legal)/modal/(.)terms/page.tsx
  src/app/(legal)/modal/page.tsx
  src/app/(legal)/page.tsx
  src/app/(legal)/privacy/page.tsx
  src/app/(legal)/terms/page.tsx
  src/app/[...not-found]/page.tsx
  src/app/about/page.tsx
  src/app/error.tsx
  src/app/find/page.tsx
  src/app/game/page.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/AuthForm/AuthForm.tsx
  src/components/Button.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/HomeSlider/HomeSlider.tsx
  src/components/Map/Map.tsx
  src/components/Modal/Modal.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavLinkItem.jsx
  tsconfig.json
Labels: documentation

#7 Protocol page
  package-lock.json
  package.json
  src/app/api/games/route.ts
  src/app/game/page.tsx
  src/components/Game/Comment/CommentTable.tsx
  src/components/Game/GameAction/GameActionBody.tsx
  src/components/Game/GameAction/GameActionTable.tsx
  src/components/Game/Protocol/GameProtocolTable.tsx
  src/components/Game/Protocol/ProtocolBody.tsx
  src/components/Game/Tournament/Tournament.tsx
  src/components/Game/Winner/WinnerTable.tsx
  src/components/Table/ButtonController.tsx
  src/components/Table/InputController.tsx
  src/lib/db/connect.ts
  src/lib/models/games.ts
  src/lib/routes/games.ts
Labels: enhancement, wontfix

#9 added tranlate for privacy and terms
  src/app/(legal)/privacy/page.tsx
  src/app/(legal)/terms/page.tsx
  src/components/Footer/Footer.tsx
  src/components/NavBar/NavLinkItem.jsx
Labels: enhancement

#13 finaly styling home page, error page
  src/app/error.tsx
  src/app/globals.css
  src/app/loading.tsx
  src/app/page.tsx
  src/components/Footer/Footer.tsx
  src/components/HamburgerButton/Hamburger.css
  src/components/HamburgerButton/HamburgerButton.tsx
  src/components/Header/Header.tsx
  src/components/Header/NavAuth.tsx
  src/components/HomeSlider/HomeSlider.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavLinkItem.tsx
Labels: enhancement

#15 added line for footer and header
  src/app/page.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
Labels: enhancement
